name: .NET Core

on:
  push:
    branches: [ develop ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Setup .NET Core 6.
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore packages.
      run: dotnet restore
    - name: Build all projects.
      run: dotnet build --configuration Release --no-restore
    - name: Unittests.
      run: dotnet test
      working-directory: ./test/Itinero.Test/
    - name: Functional tests.
      run: dotnet run -c release
      working-directory: ./test/Itinero.Test.Functional/
    - name: Nuget Pack
      run: dotnet pack -c release
      working-directory: ./src/Itinero/
    - name: Nuget Pack
      run: dotnet pack -c release
      working-directory: ./src/Itinero.IO.Osm/
    - name: Nuget Pack
      run: dotnet pack -c release
      working-directory: ./src/Itinero.IO.Shape/
    - name: Nuget Pack
      run: dotnet pack -c release
      working-directory: ./src/Itinero.Geo/
    - name: Nuget push
      run: dotnet nuget push **/*.nupkg --skip-duplicate -k ${{ secrets.NUGET_TOKEN }} -s https://api.nuget.org/v3/index.json
      working-directory: ./src/